services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - 5432:5432

    cloud-drive-browser:
        build: .
        restart: always
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - 3000:3000
