name: Publish package to GitHub Packages
on:
    push:
    workflow_dispatch:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  scope: "@ideabox"
            - run: npm run build
            - run: echo "${{ secrets.NPM_TOKEN }}"
