name: Publish package to GitHub Packages
on:
    workflow_dispatch:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
            - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
            - run: npm i
            - run: npm run build
            - run: npm publish --access public
